//program to demonstrate multiple catches
public class p42 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.out.println("main starts");
		try
		{
			int res=4/2;
			int a[]=new int[2];
			a[4]=10;
		}
		catch(ArithmeticException e)
		{
			System.out.println("Exception caught"+e);
		}
		catch(ArrayIndexOutOfBoundsException e)
		{
			System.out.println(" Array Exception caught"+e);
		}
		catch(Exception e)
		{
			System.out.println("other Exception caught"+e);
		}
		System.out.println("main ends");
	}

}

**********************output**************************************
main starts
 Array Exception caughtjava.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 2
main ends
